service: project-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  environment:
    DB_HOST: localhost
    DB_NAME: test
    DB_USER: root
    DB_PASSWORD: ""

plugins:
  - serverless-prune-versions
  - serverless-esbuild
  - serverless-offline

custom:
  prune:
    automatic: true
    number: 3

functions:
  create:
    handler: src/handlers/create.handler
    events:
      - http:
          path: /create
          method: post

  view:
    handler: src/handlers/view.handler
    events:
      - http:
          path: /view/{id}
          method: get

  update:
    handler: src/handlers/update.handler
    events:
      - http:
          path: /update/{id}
          method: put

  delete:
    handler: src/handlers/delete.handler
    events:
      - http:
          path: /delete/{id}
          method: delete
